spring:
  redis:
#    cluster:
      #(普通集群，不使用则不用开启）在群集中执行命令时要遵循的最大重定向数目。)
#      maxRedirects:
      #(普通集群，不使用则不用开启）以逗号分隔的“主机：端口”对列表进行引导。
#      nodes:
    # 连接工厂使用的数据库索引(默认为0)
    database: 0
    #连接URL，将覆盖主机，端口和密码（用户将被忽略），例如：redis://user:password@example.com:6379
    url:
    # Redis服务器主机
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    #启用SSL支持
    ssl: false
    # 连接超时时间（毫秒）
    timeout: 60000ms
#    sentinel:
      #哨兵模式，不使用则不用开启）Redis服务器的名称。
#      master:
      #（哨兵模式，不使用则不用开启）主机：端口对的逗号分隔列表。
#      nodes:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        maxActive: 200
        # 连接池中的最大空闲连接
        maxIdle: 50
        # 连接池中的最小空闲连接
        minIdle: 4
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxWait: 2ms


